### ISSUE TITLE
Auth doesn't work

### ISSUE THREAD

**Issue by fral8** [aothms/python-bimserver-client#2]
Hi,
I'm working on BIM server 1.5.117.
I have several problems on the auth process. 
I've just imported bimserver.py as class in my python Script. But when I try to log in (defining username, password and server_address [http://192.168.56.1:8082/] as strings) using:
`client = bimserver.api(server_address, username, password)` 
returns the following error.

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Desktop\python-bimserver-client-master\python-bimserver-client-master\bimserver.py", line 55, in __init__
    self.MetaInterface.getServiceInterfaces()
  File "C:\\python-bimserver-client-master\python-bimserver-client-master\bimserver.py", line 42, in <lambda>
    return lambda **kwargs: self.make_request(method, **kwargs)
  File "C:\python-bimserver-client-master\python-bimserver-client-master\bimserver.py", line 34, in make_request
    }, **({"token":self.api.token} if self.api.token else {}))).encode("utf-8"))
  File "C:\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Please someone can help me to solve the issue?
Thank you,
Francesco

**Comment by aothms** [comment]
It seems the trailing slash is the problem. On my system without / it works well. Probably easy to fix, feel free to submit a PR if interested.

~~~
>>> client = bimserver.api("localhost:8080", "admin@bimserver.org", "admin")
>>>
>>> client = bimserver.api("localhost:8080/", "admin@bimserver.org", "admin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tkrij\Downloads\bimserver.py", line 55, in __init__
    self.MetaInterface.getServiceInterfaces()
  File "C:\Users\tkrij\Downloads\bimserver.py", line 42, in <lambda>
    return lambda **kwargs: self.make_request(method, **kwargs)
  File "C:\Users\tkrij\Downloads\bimserver.py", line 34, in make_request
    }, **({"token":self.api.token} if self.api.token else {}))).encode("utf-8"))
  File "C:\Users\tkrij\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\tkrij\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\tkrij\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\tkrij\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\tkrij\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\tkrij\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
~~~
